cd ../part_install

bash install_unitree_h1_control_ws.bash
bash install_unitree_h1_teleoperation_ws.bash
bash install_unitree_h1_sensors_ws.bash
bash install_unitree_h1_point-by-point_programming_ws.bash
bash install_unitree_h1_visualization_ws.bash
bash install_unitree_h1_slam_ws.bash